### ISSUE TITLE
Tracking effort and merit, NFTs, social media, SourceCred and testing it out in TCA.

### ISSUE THREAD

**Issue by stephen-rowan** [The-Catalyst-Alliance/Catalyst-Alliance-Co-ordination#4]
## Tracking effort and merit, NFTs, social media, SourceCred and testing it out in TCA.

Thursday, 8th July, 7pm UTC (8pm BST) 

Discord context ( https://discordapp.com/channels/842027827829145611/857959078888996864/862358569134063636 ) 

### Attendees - 
- @newmindflow 
- @DanM3rcurius
- Jonathan Adjei (@jadjei)
- tyler.wales ( @wlstylr ) 
- @stephen-rowan 

### Apologies
- Victor Corcino ( @victorcorcino )

### Draft Agenda - 

-  [x] NFTs
-  [x] FTs (Fungible Tokens)
-  [x]  Social media
-  [x]  SourceCred
-  [x] Consideration of Fund 6
-  [x] TCA Tracking & Effort Working Party ?

## Tracking effort and merit in Cardano - YouTube Video
https://www.youtube.com/watch?v=Vf74Ia7UMlU&t=307s

## GitBook record
https://catalyst-swarm.gitbook.io/the-catalyst-alliance/tracking-effort-and-merit-in-cardano/tracking-working-group-july-2021#meeting-8th-july-2021

#### Tracking tools

- https://sourcecred.io/
A tool for communities to measure and reward value creation.

- https://joinseeds.earth/
Seeds is a currency that aligns money with value.
We value people, planet and prosperity for all.

- https://coordinape.com/
Scale your community with tools to reward contributors, incentivize participation and manage resources

- https://disco.coop/
The DisCO Project is a friendly and carefully planned approach for organizations that want to create and share value in ways that are cooperative, commons-oriented and rooted in feminist economics.

https://somee.social/
Social Media Redefined for privacy, end user control and monetization.

#### Resources
- Building Web Reputation Systems - Randy Farmer
https://www.youtube.com/watch?v=Yn7e0J9m6rE

### Meetings
- SourceCred Use, Set-Up and Strategy (https://github.com/Catalyst-Swarm/Catalyst-Beehive/discussions/7 )
Danielo Ospina (Aragon), Stephen Whitenstall, Tevo, Seomon (Catalyst Swarm) and Tyler Wales 
https://www.youtube.com/watch?v=kv-qXx8UvPc

**Comment by stephen-rowan** [comment]
# Rough Notes - In Draft

Google Docs Notes :  https://docs.google.com/document/d/1tooyS6GM3N9_90o0S-QQEakLylYRlaF1x0rTcS_7FB8/edit#heading=h.7cv1q0hd2z3v

## Draft Agenda -
Brief Introductions

## NFTs
New Mindflow designing an award system for Idea Fest
Could serve as a prototype
Idea Fest look at Fungible and Non-Fungible
Recognition not tracking
Tracking follows voting ( Gather votes from voting public - limited tracking)
Encouraging Participation 

Tyler - do the polls gauge the public reaction ?

1 General participation award
2 Category
3 Feedback

Johnathon
Recognition - scope of - breadth
No recognition - no reward. 
Use of NFTs
SPOCRA awards
Kudos
Honor points 
Catalyst reward roles 
CAs
vCAs
Do the NFTs accrue value in themselves - 

Dan V
Complex to mint MFTs
Use of source cred
Catalyst Metadata passport - aggregate contribution data
Vest NFT - in a faucet 

New Mindflow 
Catalyst wide recognition for non-funded proposals 
Rewards proposal teams 

Dan - CA input - 

Tyler - Funded proposals suffer from burn out
Marketing campaign for collaborative work
CAs way overworked 
Tangible results - goal oriented 

Johnathan 
Goals achievement 
Intangible activity 

## FTs (Fungible Tokens)

## Social media
So me

## SourceCred

## Consideration of Fund 6

## TCA Tracking & Effort Working Party ?
Feeding in from multiple parties
Then no transparency 
Aware to wide working group

Dan comment -
proposal proposition: an on chain binding voting app

https://github.com/adosia/Heidrun

**Comment by jadjei** [comment]
@stephen-rowan This is a link to the Miro board frame where I sketched out the potential activity streams that can feed into the reputation system.
https://miro.com/app/board/o9J_lESWSjw=/?moveToWidget=3074457360684499305&cot=14
