### ISSUE TITLE
Catalyst-Alliance SourceCred Instance Set-Up

### ISSUE THREAD

**Issue by stephen-rowan** [The-Catalyst-Alliance/Catalyst-Alliance-Co-ordination#5]
## Contributors

@tamagit80 - SecretDecks
@DanM3rcurius - SecretDecks
@wlstylr - SecretDecks
@stephen-rowan - SecretDecks, Catalyst Swarm Support

###  Owner access required to set-up SourceCred Instance  - 16/07/21

- [x] Owner access granted to @tamagit80 

### SourceCred Instance - 16/07/21

- [x] Instance created - @tamagit80 

https://github.com/The-Catalyst-Alliance/Scinstance

- [x] Owner access removed from @tamagit80
- [x] Admin invite sent to @tamagit80 on https://github.com/The-Catalyst-Alliance/SCinstance
- [x] Write access invite sent to @tamagit80  on https://github.com/The-Catalyst-Alliance/Catalyst-Alliance-Co-ordination
- [x] Allow auto-merge - set on https://github.com/The-Catalyst-Alliance/Scinstance @stephen-rowan

**Comment by tamagit80** [comment]
First installation failed, checking the code they sent me. There is an error, maybe more.

**Comment by tamagit80** [comment]
default installation completed. there are errors in the code I received from jadjei.

**Comment by jadjei** [comment]
> First installation failed, checking the code they sent me. There is an error, maybe more.
> default installation completed. there are errors in the code I received from jadjei.

Quite likely .. I rarely write anything correctly the first time! :)
Anything I can help with, please shout.
